const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json;charset=utf-8','access-control-allow-origin':'*'}});
const uid=()=>crypto.randomUUID();
async function getKV(env,k,def){const v=await env.CEEB_KV.get(k,'json');return v??def}
async function putKV(env,k,v){await env.CEEB_KV.put(k,JSON.stringify(v))}
async function log(env,user,action){const a=await getKV(env,'activities',[]);a.push({id:uid(),at:new Date().toISOString(),user,action});await putKV(env,'activities',a.slice(-500))}
async function sessionFrom(req,env){const h=req.headers.get('authorization')||'';const token=h.replace('Bearer ','');if(!token)return null;const s=await env.CEEB_KV.get('session:'+token,'json');if(!s)return null;if(s.expiresAt&&Date.now()>new Date(s.expiresAt).getTime())return null;if(s.role==='coordinator'){const cs=await getKV(env,'coordinators',[]);const c=cs.find(x=>x.id===s.id);if(!c||c.blocked)return null}return {...s,token}}
async function stateFor(env,s){let students=await getKV(env,'students',[]), invoices=await getKV(env,'invoices',[]), links=await getKV(env,'links',[]);if(s.role==='coordinator'){students=students.filter(x=>x.polo===s.polo);invoices=invoices.filter(x=>x.polo===s.polo);links=links.filter(x=>x.polo===s.polo)}return {ok:true,session:s,coordinators:s.role==='support'?await getKV(env,'coordinators',[]):[],students,invoices,links,activities:s.role==='support'?await getKV(env,'activities',[]):[]}}
export async function onRequest(context){const {request,env,params}=context;if(request.method==='OPTIONS')return json({ok:true});if(!env.CEEB_KV)return json({ok:false,error:'KV CEEB_KV não está vinculado no Cloudflare Pages.'},500);const path=(params.path||[]).join('/');try{if(path==='login'&&request.method==='POST'){const body=await request.json();const role=body.role;const key=String(body.key||'').trim();if(role==='support'){const master=env.SUPPORT_MASTER_KEY||'ceeb-suporte-2026';if(key!==master)return json({ok:false,error:'Chave do suporte inválida.'},401);const token=uid();const s={role:'support',name:'Suporte CEEB',createdAt:new Date().toISOString()};await env.CEEB_KV.put('session:'+token,JSON.stringify(s),{expirationTtl:60*60*24*30});await log(env,'Suporte','Login realizado');return json({ok:true,token})}const cs=await getKV(env,'coordinators',[]);const c=cs.find(x=>x.key===key);if(!c)return json({ok:false,error:'Chave de coordenador inválida.'},401);if(c.blocked)return json({ok:false,error:'Acesso bloqueado pelo suporte.'},403);if(c.expiresAt&&Date.now()>new Date(c.expiresAt).getTime())return json({ok:false,error:'Chave expirada. Solicite renovação ao suporte.'},403);const token=uid();const s={role:'coordinator',id:c.id,name:c.name,polo:c.polo,expiresAt:c.expiresAt,createdAt:new Date().toISOString()};await env.CEEB_KV.put('session:'+token,JSON.stringify(s),{expirationTtl:60*60*24*30});await log(env,c.name,'Login realizado');return json({ok:true,token})}
const s=await sessionFrom(request,env);if(!s)return json({ok:false,error:'Sessão inválida ou expirada.'},401);if(path==='state')return json(await stateFor(env,s));const body=request.method==='POST'?await request.json().catch(()=>({})):{};const needSupport=()=>{if(s.role!=='support')throw new Error('Apenas suporte pode executar esta ação.')};
if(path==='coordinator/create'){needSupport();const cs=await getKV(env,'coordinators',[]);if(!body.name||!body.polo||!body.key)throw new Error('Informe nome, polo e chave.');cs.push({id:uid(),name:body.name.trim(),polo:body.polo.trim(),key:body.key.trim(),expiresAt:body.expiresAt?new Date(body.expiresAt+'T23:59:59').toISOString():null,blocked:false,createdAt:new Date().toISOString()});await putKV(env,'coordinators',cs);await log(env,s.name,'Criou coordenador '+body.name);return json({ok:true})}
if(path==='coordinator/toggle'){needSupport();const cs=await getKV(env,'coordinators',[]);const c=cs.find(x=>x.id===body.id);if(!c)throw new Error('Coordenador não encontrado.');c.blocked=!c.blocked;await putKV(env,'coordinators',cs);await log(env,s.name,(c.blocked?'Bloqueou ':'Liberou ')+c.name);return json({ok:true})}
if(path==='coordinator/delete'){needSupport();let cs=await getKV(env,'coordinators',[]);const c=cs.find(x=>x.id===body.id);cs=cs.filter(x=>x.id!==body.id);await putKV(env,'coordinators',cs);await log(env,s.name,'Removeu coordenador '+(c?.name||''));return json({ok:true})}
if(path==='students/create'){const students=await getKV(env,'students',[]);const polo=s.role==='coordinator'?s.polo:body.polo;if(!body.name||!body.cpf||!polo)throw new Error('Informe nome, CPF e polo.');students.push({id:uid(),name:body.name.trim(),cpf:body.cpf.trim(),polo:polo.trim(),email:body.email||'',phone:body.phone||'',course:body.course||'',obs:body.obs||'',createdBy:s.name,createdAt:new Date().toISOString()});await putKV(env,'students',students);await log(env,s.name,'Cadastrou aluno '+body.name);return json({ok:true})}
if(path==='students/update-polo'){const polo=s.role==='coordinator'?s.polo:body.polo;if(!polo)throw new Error('Informe o polo.');const students=await getKV(env,'students',[]);let count=0;students.forEach(x=>{if(x.polo===polo){if(body.course)x.course=body.course;if(body.obs)x.obs=body.obs;count++}});await putKV(env,'students',students);await log(env,s.name,'Atualizou '+count+' alunos do polo '+polo);return json({ok:true,count})}
if(path==='students/batch'){const students=await getKV(env,'students',[]);const lines=String(body.csv||'').split(/\r?\n/).map(x=>x.trim()).filter(Boolean);let count=0;for(const line of lines){const [name,cpf,polo,email,phone,course]=line.split(',').map(x=>(x||'').trim());const finalPolo=s.role==='coordinator'?s.polo:polo;if(name&&cpf&&finalPolo){students.push({id:uid(),name,cpf,polo:finalPolo,email,phone,course,createdBy:s.name,createdAt:new Date().toISOString()});count++}}await putKV(env,'students',students);await log(env,s.name,'Importou '+count+' alunos em lote');return json({ok:true,count})}
if(path==='invoices/create'){const invoices=await getKV(env,'invoices',[]),links=await getKV(env,'links',[]);const polo=s.role==='coordinator'?s.polo:body.polo;if(!body.name||!body.cpf||!polo||!body.value)throw new Error('Informe nome, CPF, polo e valor.');const inv={id:uid(),name:body.name,cpf:body.cpf,polo,value:Number(body.value),due:body.due||'',desc:body.desc||'',status:'Aguardando pagamento',createdBy:s.name,createdAt:new Date().toISOString()};invoices.push(inv);links.push({id:uid(),invoiceId:inv.id,name:inv.name,polo:inv.polo,value:inv.value,url:`https://pagamento.ceeb.local/fatura/${inv.id}`,createdAt:inv.createdAt});await putKV(env,'invoices',invoices);await putKV(env,'links',links);await log(env,s.name,'Emitiu fatura manual para '+body.name);return json({ok:true})}
if(path==='invoices/by-polo'){const polo=s.role==='coordinator'?s.polo:body.polo;if(!polo||!body.value)throw new Error('Informe polo e valor.');const students=await getKV(env,'students',[]);const invoices=await getKV(env,'invoices',[]),links=await getKV(env,'links',[]);let count=0;students.filter(x=>x.polo===polo).forEach(st=>{const inv={id:uid(),name:st.name,cpf:st.cpf,polo,value:Number(body.value),due:body.due||'',desc:body.desc||'',status:'Aguardando pagamento',createdBy:s.name,createdAt:new Date().toISOString()};invoices.push(inv);links.push({id:uid(),invoiceId:inv.id,name:inv.name,polo:inv.polo,value:inv.value,url:`https://pagamento.ceeb.local/fatura/${inv.id}`,createdAt:inv.createdAt});count++});await putKV(env,'invoices',invoices);await putKV(env,'links',links);await log(env,s.name,'Emitiu '+count+' faturas do polo '+polo);return json({ok:true,count})}
if(path==='links/clear'){await putKV(env,'links',s.role==='coordinator'?(await getKV(env,'links',[])).filter(x=>x.polo!==s.polo):[]);await log(env,s.name,'Limpou lista de links');return json({ok:true})}
return json({ok:false,error:'Rota não encontrada: '+path},404)}catch(e){return json({ok:false,error:e.message},400)}}
